name: test
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.0
  http: ^0.13.4
  # ssl_pinning_plugin: ^2.0.0
  flutter_bloc: ^8.1.1
  dio: ^4.0.6
  file_picker: ^6.1.1
  # device_info_plus: ^9.1.1
  android_id: ^0.1.3+1
  webview_flutter: ^4.2.2
  # platform_device_id: ^1.0.1
  flutter_secure_storage: ^8.0.0
  provider: ^6.0.5
  google_mlkit_object_detection: ^0.11.0
  image_picker: ^0.8.5
  google_mlkit_image_labeling: ^0.10.0
  persistent_bottom_nav_bar_v2: ^5.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/lang/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
